# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kakuweb Blog
tagline:          Rants and raves. Some interesting stuff, most of it not.
description:      Hodgepodge bunch of stuff, mostly related to programming but really anything I feel like ranting about.
url:              http://kakubei.github.io

author:
  name:           Alex Dearden
  url:            https://twitter.com/kakubei

paginate:         1

# Use this if you want to build a top menu of certain pages
#pages_list:
#  About: '/about'
#  Archive: '/archive'

# Custom vars
version:          0.5
#
#github:
#  repo:           https://github.com/poole/poole
